### ISSUE TITLE
ssh broken on v2.7.5+rev2

### ISSUE THREAD

**Issue by floion** [resin-os/resin-imx6ul-var-dart#29]
Trying to ssh to the host OS:

ssh_dispatch_run_fatal: Connection to UNKNOWN port 65535: incorrect signature
Killed by signal 1.

**Comment by spanceac** [comment]
The problem is introduced by the commit 40817dd57fc4d0bd024c935931141cd96278a6f7 from meta-resin.
This commit enables compile security features like stack protection, PIE.
Will continue investigation to see why these features affect the expected functionality of dropbear binary.

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-imx6ul-var-dart/pull/32
