### ISSUE TITLE
Replace DOCKER_STORAGE by BALENA_STORAGE

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-imx6ul-var-dart#38]
Current configuration still uses the old DOCKER_STORAGE variable. Please update it accordingly since the new meta-resin renamed that to BALENA_STORAGE.

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-imx6ul-var-dart/pull/39

**Comment by floion** [comment]
PR with the fix merged. Closing this issue
